# Generated by Django 4.1.2 on 2022-10-27 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_qrcode_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='nom',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='postnom',
        ),
    ]
