# Generated by Django 4.1.2 on 2022-10-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_qrcode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myqrcode',
            name='image',
        ),
        migrations.AddField(
            model_name='myqrcode',
            name='qr_code',
            field=models.ImageField(default=1, upload_to='qrcode/'),
            preserve_default=False,
        ),
    ]
