# Generated by Django 4.1.2 on 2022-10-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_qrcode', '0002_remove_myqrcode_image_myqrcode_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myqrcode',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qrcode/'),
        ),
    ]
