# Generated by Django 4.1.2 on 2022-10-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_qrcode', '0003_alter_myqrcode_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='myqrcode',
            name='image',
            field=models.ImageField(default=1, upload_to='profile/'),
            preserve_default=False,
        ),
    ]
